apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  template:
    metadata:
      name: hello-job
    spec:
      containers:
        - name: hello-job
          image: busybox
          command: ["echo", "Hello-my-first-job"]
      restartPolicy: OnFailure