apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: service-app
    spec:
      containers:
        - name: service-container
          image: education/service:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8443
  selector:
    matchLabels:
      app: service-app
